# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["aoc-2022@runjak.codes"]
description = "Let's turn to the cloud and see how it would look like to tackle AoC 2022 using Fastly Compute@Edge"
language = "rust"
manifest_version = 2
name = "aoc-2022"
service_id = "U6bfqd9Cu5flDMGYttFt17"

[scripts]
  build = "cargo build --bin fastly-compute-project --release --target wasm32-wasi --color always"
